# Общие настройки отладки
debug_mode: false

# Оптимизация CPU
cpu_optimization:
  enabled: true
  interval_seconds: 60
  reset_far_mob_target: true # Сбрасывать цель мобов, находящихся далеко от игроков
  mob_despawn_radius: 64 # Радиус, в котором моб считается "близко к игроку"

# Оптимизация памяти
memory_optimization:
  enabled: true
  interval_seconds: 300 # Каждые 5 минут

# Оптимизация чанков
chunk_optimization:
  enabled: true
  interval_seconds: 300 # Каждые 5 минут
  unload_radius: 8 # Радиус в чанках, за пределами которого чанки могут быть выгружены (от игрока)
  safe_unload: true # Выгружать чанки, только если нет активных игроков/сущностей (требует более сложной логики)

# Принудительная граница мира
world_border_enforcement:
  enabled: true
  interval_seconds: 30
  border_size: 10000 # Размер мира (от -10000 до 10000 по X/Z)
  teleport_world: world # Мир для телепортации при выходе за границу
  teleport_location:
    x: 0.0
    y: 100.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0